#docker-compose up
version: "3.9"
services:
  deploy:
    container_name: MedonicM20App
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresSQLDBMedonicM20:5432/medonic_db
      - SPRING_DATASOURCE_USERNAME=medonic
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      java16-network:
        aliases:
          - medonicdb
networks:
  java16-network:
    name: 'medonic_network'