#docker-compose up
version: "3.9"
services:
  postgres:
    container_name: PostgresSQLDBMedonicM20
    image: postgres
    environment:
      POSTGRES_DB: "medonic_db"
      POSTGRES_USER: "medonic"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    networks:
      medonic-network:
        aliases:
          - medonicdb
networks:
  medonic-network:
    name: 'medonic_network'


